
shallow_clone: true

os:
  - Visual Studio 2017

build:
  verbosity: detailed

branches:
  only:
    - master

install:
  ############################################################################
  # Install EiffelStudio 
  ############################################################################
  - mkdir C:\projects\eiffel
  - cd C:\projects\eiffel

  - set EIFFELSTUDIO_URL="https://goo.gl/1RQMG7"
  - appveyor DownloadFile %EIFFELSTUDIO_URL% -FileName eiffel_studio.zip
  - 7z x eiffel_studio.zip -oC:\projects\eiffel\ > nul
  - cmd: set ISE_C_COMPILER=msc_vc140
  - cmd: set ISE_PLATFORM=win64
  - cmd: set ISE_EIFFEL=C:\projects\eiffel\Eiffel_17.11 
  - cmd: set PATH=%PATH%;%ISE_EIFFEL%/studio/spec/%ISE_PLATFORM%/bin;
  - cmd: set PATH=%PATH%;%ISE_EIFFEL%/tools/spec/%ISE_PLATFORM%/bin;
  - ec -version
  - compile_all -version

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat" amd64

build_script:
  - cd C:\projects
  - git clone https://github.com/EiffelWebFramework/HAL
  - cd HAL
  - compile_all -ecb -melt -list_failures -clean -options dotnet=false

