language: eiffel
before_script:
  - export current_dir=$PWD ; echo current_dir=$current_dir ; cd ..
  - export ISE_EIFFEL=$PWD/Eiffel_17.11; 
  - export ISE_PLATFORM=linux-x86-64
  - curl -sSL https://ftp.eiffel.com/pub/beta/nightly/Eiffel_17.11_gpl_100608-linux-x86-64.tar.bz2 | tar -x --bzip2
  - export PATH=$PATH:$ISE_EIFFEL/studio/spec/$ISE_PLATFORM/bin:$PATH:$ISE_EIFFEL/tools/spec/$ISE_PLATFORM/bin
  - echo `ec -version`
  - cd $current_dir

# safelist
branches:
  only:
  - master

script: 
  #compile code  
  - compile_all -ecb -melt -list_failures -log_verbose -clean -options dotnet=false
  #testing
  - ec -config test/test_suite.ecf -c_compile -tests 

